### ISSUE TITLE
中文引号和感叹号放一起的时候有一定重叠

### ISSUE THREAD

**Issue by Yan-Zero** [lxgw/yozai-font#4]
![image](https://user-images.githubusercontent.com/32036413/203585961-d49557b5-d5de-48b0-8bb7-a264189f92de.png)
如图，上边是悠哉字体，下边是霞鹜文楷 GB。
微软雅黑：
![image](https://user-images.githubusercontent.com/32036413/203586190-a9789935-b3f4-437a-a2ab-81832e53dea5.png)

**Comment by lxgw** [comment]
这款字体已经好久不更新了。

**Comment by Yan-Zero** [comment]
> 这款字体已经好久不更新了。

呜呜呜
另外，Readme 的链接放成小赖字体的了。

**Comment by yatounoneko** [comment]
![image](https://user-images.githubusercontent.com/22129910/206913046-1914bd49-6e5c-4ba2-8dab-9aa7a657a4bb.png)
不覺得有什麼問題呀？
